#开启调试
Debug = true
#http端口
Port = 9090
#db名称
DBName = "n9e"
#tdengine连接方式 restful go
TDengineConnType = "go"
#数据保存天数
DataKeep = 3650
#历史数据插入策略
Update = 1
#是否显示 SQL
ShowSQL = true
#是否启用 GZip
EnableGzip = false
#日志等级 "panic" "fatal" "error" "warn" "info" "debug" "trace"
LogLevel = "info"
#goroutinue 池大小
GoPoolSize = 50000
#insert的worker
StoreWorker = 100

[[TDengineGo]]
#地址
Address = "root:taosdata@/tcp(127.0.0.1:6030)/"
#最大空闲连接
MaxIdle = 20
#最大连接数
MaxOpen = 200
#连接最长生命周期（秒）
MaxLifetime = 30

#[[TDengineRestful]]
##连接地址
#Address = "http://127.0.0.1:6041"
##验证方式 Basic Taosd
#AuthType = "Basic"
##用户名
#Username = "root"
##密码
#Password = "taosdata"
##每个host最大连接数 -1代表无限制
#MaxConnsPerHost = 10